
version: "3.9"
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  api:
    build: ./api
    depends_on:
      - mongo
    environment:
      - PORT=8080
      - MONGO_URI=mongodb://mongo:27017/helpdesk
      - JWT_SECRET=change-me
      - AUTO_CLOSE_ENABLED=true
      - CONFIDENCE_THRESHOLD=0.78
      - STUB_MODE=true
      - NODE_ENV=development
    ports:
      - "8080:8080"
  client:
    build: ./client
    depends_on:
      - api
    environment:
      - VITE_API_URL=http://localhost:8080
    ports:
      - "5173:5173"
volumes:
  mongo_data:
